-- require("transparent").setup({
--     extra_groups = {
--     "NormalFloat",       -- plugins which have float panel such as Lazy, Mason, LspInfo
--     "Normal",
--     "NvimTreeNormal",    -- NvimTree
--     "BufferTabpageFill", -- Barbar
--     "TelescopeNormal",   -- Telescope
--     "DevIconLuaVisible",
--     "BufferVisibleSign",
--     "BufferVisible",
--     "DevIconLuaInactive",
--     "BufferInactiveSign",
--     "BufferInactive",
--     "DevIconLuau",
--     "BufferTabpageFill",
--     "Comment",
--     "NvimTreeCursorLine",
--     "ColorColumn"
--   },
-- })
